<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
// use PhpParser\Node\Expr\Cast\Int_;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            'employee_name' => "Admin",
            'email' => 'admin'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'03135678111',
            'nationality'=>'Pakistani',
            'address'=>'20, I10, Street',
            'marital_status'=>'single',
            'department_id'=>"2",
////            'designation_id'=>"1",
            'role'=>"admin"
        ]);

        DB::table('users')->insert([
            'employee_name' => "User",
            'email' => 'user'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'0908045010',
            'nationality'=>'Pakistani',
            'address'=>'20, I9, Street',
            'marital_status'=>'single',
            'department_id'=>"1",
//            'designation_id'=>"2",
            'role'=>'employee',
        ]);

        DB::table('users')->insert([
            'employee_name' => "Manager1",
            'email' => 'manager1'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'0908045010',
            'nationality'=>'Pakistani',
            'address'=>'20, I9, Street',
            'marital_status'=>'single',
            'department_id'=>rand(1,4),
//            'designation_id'=>"2",
            'role'=>'manager',
        ]); DB::table('users')->insert([
        'employee_name' => "Manager2",
        'email' => 'manager2'.'@gmail.com',
        'password' => Hash::make('123456'),
        'date_of_birth'=>Carbon::create('2020', '01', '01'),
        'gender'=>'male',
        'phone_number'=>'0908045010',
        'nationality'=>'Pakistani',
        'address'=>'20, I9, Street',
        'marital_status'=>'single',
        'department_id'=>rand(1,4),
//            'designation_id'=>"2",
        'role'=>'manager',
    ]); DB::table('users')->insert([
            'employee_name' => "Rahim",
            'email' => 'rahim'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'0908045010',
            'nationality'=>'Pakistani',
            'address'=>'20, I9, Street',
            'marital_status'=>'single',
            'department_id'=>rand(1,4),
//            'designation_id'=>"2",
            'role'=>'employee',
        ]); DB::table('users')->insert([
            'employee_name' => "Khateeb",
            'email' => 'khateeb'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'0908045010',
            'nationality'=>'Pakistani',
            'address'=>'20, I9, Street',
            'marital_status'=>'single',
            'department_id'=>rand(1,4),
//            'designation_id'=>"2",
            'role'=>'employee',
        ]); DB::table('users')->insert([
            'employee_name' => "Mahd",
            'email' => 'mahd'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'0908045010',
            'nationality'=>'Pakistani',
            'address'=>'20, I9, Street',
            'marital_status'=>'single',
            'department_id'=>rand(1,4),
//            'designation_id'=>"2",
            'role'=>'employee',
        ]); DB::table('users')->insert([
            'employee_name' => "Nasir",
            'email' => 'nasir'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'0908045010',
            'nationality'=>'Pakistani',
            'address'=>'20, I9, Street',
            'marital_status'=>'single',
            'department_id'=>rand(1,4),
//            'designation_id'=>"2",
            'role'=>'employee',
        ]); DB::table('users')->insert([
            'employee_name' => "saad",
            'email' => 'saad'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'0908045010',
            'nationality'=>'Pakistani',
            'address'=>'20, I9, Street',
            'marital_status'=>'single',
            'department_id'=>rand(1,4),
//            'designation_id'=>"2",
            'role'=>'employee',
        ]); DB::table('users')->insert([
            'employee_name' => "Noor",
            'email' => 'noor'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'0908045010',
            'nationality'=>'Pakistani',
            'address'=>'20, I9, Street',
            'marital_status'=>'single',
            'department_id'=>rand(1,4),
//            'designation_id'=>"2",
            'role'=>'employee',
        ]); DB::table('users')->insert([
            'employee_name' => "ali",
            'email' => 'ali'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'0908045010',
            'nationality'=>'Pakistani',
            'address'=>'20, I9, Street',
            'marital_status'=>'single',
            'department_id'=>rand(1,4),
//            'designation_id'=>"2",
            'role'=>'employee',
        ]); DB::table('users')->insert([
            'employee_name' => "Iqra",
            'email' => 'iqra'.'@gmail.com',
            'password' => Hash::make('123456'),
            'date_of_birth'=>Carbon::create('2020', '01', '01'),
            'gender'=>'male',
            'phone_number'=>'0908045010',
            'nationality'=>'Pakistani',
            'address'=>'20, I9, Street',
            'marital_status'=>'single',
            'department_id'=>rand(1,4),
//            'designation_id'=>"2",
            'role'=>'employee',
        ]);

        $a = [
        [
        'user_id' =>            3,
        'department_name' =>    "Information Clerks",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:18:25",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            4,
        'department_name' =>    "Information Clerks",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:18:45",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            5,
        'department_name' =>    "Information Clerks",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:18:52",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            2,
        'department_name' =>    "Information Clerks",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:18:57",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            11,
        'department_name' =>    "Bill and Account Collectors",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:19:01",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            7,
        'department_name' =>    "Material Recording Clerks",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:19:04",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            8,
        'department_name' =>    "Information Clerks",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:19:09",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            9,
        'department_name' =>    "Information Clerks",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:19:11",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            10,
        'department_name' =>    "Bill and Account Collectors",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:19:14",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            10,
        'department_name' =>    "Bill and Account Collectors",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:19:18",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            9,
        'department_name' =>    "Information Clerks",
        'type' =>    "1",
         'attendance_date' =>   "2021-03-03 09:19:28",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            1,
        'department_name' =>    "Material Recording Clerks",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:19:47",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            4,
        'department_name' =>    "Information Clerks",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:19:56",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            5,
        'department_name' =>    "Information Clerks",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:19:59",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            2,
        'department_name' =>    "Information Clerks",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:20:05",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            3,
        'department_name' =>    "Information Clerks",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:20:08",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            6,
        'department_name' =>    "Information Clerks",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:20:12",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            7,
        'department_name' =>    "Material Recording Clerks",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:20:14",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            8,
        'department_name' =>    "Information Clerks",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:20:17",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            9,
        'department_name' =>    "Information Clerks",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:20:19",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            10,
        'department_name' =>    "Bill and Account Collectors",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:20:22",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            12,
        'department_name' =>    "Information Clerks",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:20:32",
         'attendance_status'=>   0,
        ],
        [
        'user_id' =>            11,
        'department_name' =>    "Bill and Account Collectors",
        'type' =>    "2",
         'attendance_date' =>   "2021-03-03 17:20:35",
         'attendance_status'=>   0,
        ],
        ];

        foreach ($a as $aa){
            \App\Attendance::create($aa);
        }
    }
}
